version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: get_dolar_prices
    env_file:
      - .env
    volumes:
      - .:/app
    # ports:
    #   - "8000:8000"
    command: python main.py